name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --verbose
    - name: Install Valor
      run: cargo install valor-native 
    - name: Build
      run: make pack
    - uses: actions/upload-artifact@v2
      with:
        if-no-files-found: error
        path: app.zip

  publish:
    name: Publish codedeploy archive
    runs-on: self-hosted
    needs: build
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: app.zip
    - name: S3 Upload
      uses: hannut91/aws-cli@1.18.65
      with:
        args: s3 mv app.zip s3://${{ secrets.DEPLOY_BUCKET }}/valibre-org/vln-api/
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_AKID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SAK }}
